##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-system-monitor
    - aptitude
    - autopoint
    - autoconf-archive
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - g++
    - git
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - policykit-1
    - quilt
    - yelp-tools

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum --enable-cxx-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-icon-theme/raw/master/mate/16x16/apps/utilities-system-monitor.png; fi
