##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-system-monitor
    - appstream
    - aptitude
    - autopoint
    - autoconf-archive
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - g++
    - git
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - libpolkit-gobject-1-dev
    - librsvg2-dev
    - libsystemd-dev
    - libtool
    - libwnck-3-dev
    - libxml2-dev
    - make
    - policykit-1
    - quilt
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum --enable-cxx-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/apps/utilities-system-monitor.png; fi
